name: audio_player
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  audio_video_progress_bar: ^1.0.1
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    -  assets/audio/Davidofall.mp3
    -  assets/audio/Burnaboyitsplenty.mp3
